[build-system]
requires = ["setuptools >=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "keras-paddle"
authors = [
    {name = "Keras team", email = "keras-users@googlegroups.com"},
]
description = "PaddlePaddle backend for Keras"
readme = "README.md"
requires-python = ">=3.11"
license = {text = "Apache License 2.0"}
dynamic = ["version"]
classifiers = [
    "Development Status :: 4 - Beta",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "Programming Language :: Python :: 3 :: Only",
    "Operating System :: Unix",
    "Operating System :: MacOS",
    "Intended Audience :: Science/Research",
    "Topic :: Scientific/Engineering",
    "Topic :: Software Development",
]
dependencies = [
    "keras",
    "numpy",
    "paddlepaddle",
]

[project.urls]
Home = "https://keras.io/"
Repository = "https://github.com/keras-team/keras-paddle"

[tool.setuptools.dynamic]
version = {attr = "keras_paddle.src.version.__version__"}

[tool.ruff]
line-length = 80

[tool.ruff.lint]
select = [
    "E",  # pycodestyle error
    "F",  # Pyflakes
    "I",  # isort
    "S101",  # flake8-bandit / use of assert detected
]

[tool.ruff.lint.per-file-ignores]
"**/__init__.py" = ["E501", "F401"]  # lines too long; imported but unused

[tool.ruff.lint.isort]
force-single-line = true
known-first-party = ["keras", "keras_paddle"]
