name: Tests

on:
  push:
    branches: [ main ]
  pull_request:
  release:
    types: [created]

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  run_cpu_tests:
    strategy:
      matrix:
        os: [ubuntu-latest]
      fail-fast: false

    name: Run tests on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    timeout-minutes: 120

    env:
      KERAS_HOME: ../keras-paddle/.github/workflows/config

    steps:
      - name: Set up Python
        uses: actions/setup-python@5fda3b95a4ea91299a34e894583c3862153e4b97 # v7.0.0
        with:
          python-version: '3.11'

      - name: Checkout keras-paddle ${{ github.ref }}
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          path: keras-paddle
          persist-credentials: false
 
      - name: Checkout keras
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          repository: keras-team/keras
          ref: pluggable_backend
          path: keras
          persist-credentials: false
 
      - name: Install Python dependencies
        run: |
          pip install -r keras/requirements-common.txt
          pip install -r keras-paddle/requirements.txt

      - name: Install keras-paddle
        working-directory: ./keras-paddle
        run: pip install -e .

      - name: Verify installation
        working-directory: ./keras
        run: python -c "import keras; assert keras.backend.backend() == 'paddle'; import keras_paddle; print(keras_paddle.__version__)"

      - name: Run Tests
        working-directory: ./keras
        run: pytest keras --ignore keras/src/applications --ignore keras/src/wrappers

  format:
    name: Check the code format
    runs-on: ubuntu-latest

    steps:
      - name: Checkout keras-paddle ${{ github.ref }}
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          persist-credentials: false

      - name: Set up Python
        uses: actions/setup-python@5fda3b95a4ea91299a34e894583c3862153e4b97 # v7.0.0
        with:
          python-version: '3.11'

      - name: Install ruff
        run: pip install ruff

      - name: Check the code format
        run: |
          ruff check .
          ruff format --check .
